# Question: https://projecteuler.net/problem=140

# SageMath:
"""
sage: C.<x> = CFiniteSequences(QQ)
sage: C.guess([0,1,4,5,9,14,23])
C-finite sequence, generated by (-3*x^2 - x)/(x^2 + x - 1)
"""

# (-3*x^2 - x)/(x^2 + x - 1) = y; x \in Q, y \in N
# -3x^2-x = yx^2 + yx - y
# (y+3)x^2 + (y+1)x - y = 0
# https://www.wolframalpha.com/input/?i=%28y%2B3%29x%5E2+%2B+%28y%2B1%29x+-+y+%3D+0
# x = ((-y - 1) ± sqrt((y + 1)^2 + 4 y (y + 3)))/(2 (y + 3))
# x = (sqrt((y+1)^2+4(y^2+3y))+(y-1))/(2y+6)

# x is rational when (y+1)^2+4(y^2+3y)= L^2 for some L \in N
# https://www.wolframalpha.com/input/?i=%28y%2B1%29%5E2%2B4%28y%5E2%2B3y%29%3D+L%5E2+positive+integer+solutions
# L = 1/5 (35 (9 - 4 sqrt(5))^(2 n) - 16 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 35 (9 + 4 sqrt(5))^(2 n) + 16 sqrt(5) (9 + 4 sqrt(5))^(2 n)) and y = 1/5 (16 (9 - 4 sqrt(5))^(2 n) - 7 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 16 (9 + 4 sqrt(5))^(2 n) + 7 sqrt(5) (9 + 4 sqrt(5))^(2 n) - 7) and n>=0 and n element Z
# L = 1/5 (125 (9 - 4 sqrt(5))^(2 n) - 56 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 125 (9 + 4 sqrt(5))^(2 n) + 56 sqrt(5) (9 + 4 sqrt(5))^(2 n)) and y = 1/5 (56 (9 - 4 sqrt(5))^(2 n) - 25 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 56 (9 + 4 sqrt(5))^(2 n) + 25 sqrt(5) (9 + 4 sqrt(5))^(2 n) - 7) and n>=0 and n element Z
# L = 1/10 (35 (9 - 4 sqrt(5))^(2 n) - 17 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 35 (9 + 4 sqrt(5))^(2 n) + 17 sqrt(5) (9 + 4 sqrt(5))^(2 n)) and y = 1/10 (17 (9 - 4 sqrt(5))^(2 n) - 7 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 17 (9 + 4 sqrt(5))^(2 n) + 7 sqrt(5) (9 + 4 sqrt(5))^(2 n) - 14) and n>=0 and n element Z
# L = 1/10 (485 (9 - 4 sqrt(5))^(2 n) - 217 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 485 (9 + 4 sqrt(5))^(2 n) + 217 sqrt(5) (9 + 4 sqrt(5))^(2 n)) and y = 1/10 (217 (9 - 4 sqrt(5))^(2 n) - 97 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 217 (9 + 4 sqrt(5))^(2 n) + 97 sqrt(5) (9 + 4 sqrt(5))^(2 n) - 14) and n>=0 and n element Z
# L = 1/10 (-5 (9 - 4 sqrt(5))^(2 n) - 7 sqrt(5) (9 - 4 sqrt(5))^(2 n) - 5 (9 + 4 sqrt(5))^(2 n) + 7 sqrt(5) (9 + 4 sqrt(5))^(2 n)) and y = 1/10 (7 (9 - 4 sqrt(5))^(2 n) + sqrt(5) (9 - 4 sqrt(5))^(2 n) + 7 (9 + 4 sqrt(5))^(2 n) - sqrt(5) (9 + 4 sqrt(5))^(2 n) - 14) and n>=1 and n element Z
# L = 1/10 (5 (9 - 4 sqrt(5))^(2 n) - 7 sqrt(5) (9 - 4 sqrt(5))^(2 n) + 5 (9 + 4 sqrt(5))^(2 n) + 7 sqrt(5) (9 + 4 sqrt(5))^(2 n)) and y = 1/10 (7 (9 - 4 sqrt(5))^(2 n) - sqrt(5) (9 - 4 sqrt(5))^(2 n) + 7 (9 + 4 sqrt(5))^(2 n) + sqrt(5) (9 + 4 sqrt(5))^(2 n) - 14) and n>=1 and n element Z

from decimal import *
getcontext().prec = 64

ans = 0

N = 30
sqrt5 = Decimal(5).sqrt()

y1 = lambda n: Decimal(0.2)*(16*(9-4*sqrt5)**(2*n)-7*sqrt5*(9-4*sqrt5)**(2*n)+16*(9+4*sqrt5)**(2*n)+7*sqrt5*(9+4*sqrt5)**(2*n)-7)
y2 = lambda n: Decimal(0.2)*(56*(9-4*sqrt5)**(2*n)-25*sqrt5*(9-4*sqrt5)**(2*n)+56*(9+4*sqrt5)**(2*n)+25*sqrt5*(9+4*sqrt5)**(2*n)-7)
y3 = lambda n: Decimal(0.1)*(17*(9-4*sqrt5)**(2*n)-7*sqrt5*(9-4*sqrt5)**(2*n)+17*(9+4*sqrt5)**(2*n)+7*sqrt5*(9+4*sqrt5)**(2*n)-14)
y4 = lambda n: Decimal(0.1)*(217*(9-4*sqrt5)**(2*n)-97*sqrt5*(9-4*sqrt5)**(2*n)+217*(9+4*sqrt5)**(2*n)+97*sqrt5*(9+4*sqrt5)**(2*n)-14)
y5 = lambda n: Decimal(0.1)*(7*(9-4*sqrt5)**(2*n)+sqrt5*(9-4*sqrt5)**(2*n)+7*(9+4*sqrt5)**(2*n)-sqrt5*(9+4*sqrt5)**(2*n)-14)
y6 = lambda n: Decimal(0.1)*(7*(9-4*sqrt5)**(2*n)-sqrt5*(9-4*sqrt5)**(2*n)+7*(9+4*sqrt5)**(2*n)+sqrt5*(9+4*sqrt5)**(2*n)-14)

ys = [1]

for n in range(N):
    ys.append(int(y1(n)))
    ys.append(int(y2(n)))
    ys.append(int(y3(n)))
    ys.append(int(y4(n)))
    ys.append(int(y5(n)))
    ys.append(int(y6(n)))

ys = sorted(ys)

while ys[0] < 2:
    del ys[0]

ans = sum(ys[:N])
print(ans)